# Primeira aula de python
# comandos 
# print comando para apresentar mensagens 
print("meu nome é: Ana \n")
print ("\n meu curso é Desenvolvimento \n de Sistemas\n")
print ("eu tenho 16 anos \n " + "gosto de fazer cílios")
# o sinal de + é para juntar (concatenar) frases 

# print com numeros 
print (10)
print ("10+5")
print ( "somar valoes", 10+5)
print ("subtrair valores", 10-5)
print ("dividir valoes", 10/5)
print ("multiplicar valores", 10*5)
print ("resolver expoentes", 10**5)

# operadores matemáticos 
# soma +
# subtração -
# divisão /
# multiplicação * 
# expoente ** ou ^2 

#  inpunt permite inserir valores númericos ou strings (textos)

print ("cálculos")
print("iniciar cálculos")
# variáveis 
# armarzenar infotmações
# pv1 nome da variável para armazernar o primeiro valor 
# pv2 nome da variável paraq armazenar o segundo valor 
# str significa inserir valores (strings)
# int deve manter apenas valores inteiros númericos 
# float permite inserir valores com casas decimais 
pv1 = int(input("digite o primeiro valor: \n"))
pv2 = int(input("digite o segundo valor: \n"))
print ("o resultado é", pv1+pv2)
pv3 = int(input("digite o terceiro valor: \n"))
pv4 = int(input("digite o quarto valor: \n"))
print ("o resultado da subtração é", pv1-pv2)
# variáveis com texto 
mult1 = int(input("digite o quinto valor: \n"))
mult2 = int(input("digite o sexto valor: \n"))
mtotal = mult1 * mult2 
print ("o valor da multiplicação é:" , mtotal)